# Generated by Django 5.0.3 on 2024-03-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_rename_id_curso_cursos_idcurso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
